/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import DTO.DuongBayDTO;
import DAO.DuongBayDAO;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Anh Huy
 */
public class SuaDuongBayGUI1 extends javax.swing.JFrame {
    DuongBayDAO dao = new DuongBayDAO();
    private DuongBayDTO duongBay;
    /**
     * Creates new form SuaDuongBayGUI
     */
    public SuaDuongBayGUI1(DuongBayDTO duongBay) {
        DuongBayDAO dao = new DuongBayDAO();
        initComponents();
        this.duongBay = duongBay;
        DuongBayGUI gui = new DuongBayGUI();
        ArrayList<String> tp = getThanhPho();
        for (String i : tp){
            cbo_noiDi1.addItem(i);
        }
        for (String i : tp){
            cbo_noiDen1.addItem(i);
        }
        txt_maDB1.setEditable(false);
        txt_maDB1.setText(duongBay.getMaDuongBay());
        cbo_noiDi1.setSelectedItem(duongBay.getNoiDi());
        cbo_noiDen1.setSelectedItem(duongBay.getNoiDen());
        cbo_noiDi1.setEnabled(false);
        cbo_noiDen1.setEnabled(false);
        String thoiGian = duongBay.getThoiGianBay();

    // Tách chuỗi thời gian thành các phần giờ, phút và giây
    String[] parts = thoiGian.split(":");
    if (parts.length == 3) {
        try {
            int gio = Integer.parseInt(parts[0]);
            int phut = Integer.parseInt(parts[1]);
            int giay = Integer.parseInt(parts[2]);

            // Đặt giá trị cho Spinner giờ, phút và giây
            spn_gio1.setValue(gio);
            spn_phut1.setValue(phut);
            spn_giay1.setValue(giay);
        } catch (NumberFormatException e) {
            // Xử lý lỗi nếu có
            e.printStackTrace();
        }
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_maDB1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        cbo_noiDi1 = new javax.swing.JComboBox<>();
        cbo_noiDen1 = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        spn_gio1 = new javax.swing.JSpinner();
        spn_phut1 = new javax.swing.JSpinner();
        spn_giay1 = new javax.swing.JSpinner();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Mã đường bay");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Nơi đi");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Nơi đến");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Thời gian ước tính");

        jButton1.setBackground(new java.awt.Color(153, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Lưu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(153, 255, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Hủy");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(153, 255, 255));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Khai thác lại");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        spn_gio1.setModel(new javax.swing.SpinnerNumberModel(0, 0, 24, 1));

        spn_phut1.setModel(new javax.swing.SpinnerNumberModel(0, 0, 59, 1));

        spn_giay1.setModel(new javax.swing.SpinnerNumberModel(0, 0, 59, 1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(spn_gio1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(spn_phut1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cbo_noiDen1, 0, 150, Short.MAX_VALUE)
                                .addComponent(cbo_noiDi1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_maDB1))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(38, 38, 38)
                        .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jButton2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(spn_giay1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_maDB1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbo_noiDi1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbo_noiDen1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(spn_gio1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spn_phut1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spn_giay1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69))
        );

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Sửa đường bay");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DuongBayDTO db = getModelUpdate();
        if (dao.update(db)>0){
            JOptionPane.showMessageDialog(this, "Sửa thành công");
            fillTable1();
        }else{
            JOptionPane.showMessageDialog(this, "Sửa thất bại");
        }
        this.dispose();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      showComfirmRemove();
      this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
   

public DuongBayDTO getModelUpdate(){
        DuongBayDTO db = new DuongBayDTO();
        db.setMaDuongBay(txt_maDB1.getText());
        db.setNoiDi(cbo_noiDi1.getSelectedItem().toString());
        db.setNoiDen(cbo_noiDen1.getSelectedItem().toString());
        int gio = (int) spn_gio1.getValue();
        int phut = (int) spn_phut1.getValue();
        int giay = (int) spn_giay1.getValue();
        String thoiGian = String.format("%02d:%02d:%02d", gio, phut, giay);
        db.setThoiGianBay(thoiGian);
        db.setNoiNgoai(1);
        db.setXuLy(1);
        return db;
    }
    public void setModel(DuongBayDTO db){
        txt_maDB1.setText(db.getMaDuongBay());
        cbo_noiDi1.setSelectedItem(db.getNoiDi());
        cbo_noiDen1.setSelectedItem(db.getNoiDen());
        String thoiGian = db.getThoiGianBay();
        String[] parts = thoiGian.split(":");
    if (parts.length == 3) {
        try {
            int gio = Integer.parseInt(parts[0]);
            int phut = Integer.parseInt(parts[1]);
            int giay = Integer.parseInt(parts[2]);
            spn_gio1.setValue(gio);
            spn_phut1.setValue(phut);
            spn_giay1.setValue(giay);
        } catch (NumberFormatException e) {
            // Xử lý lỗi nếu có
            e.printStackTrace();
        }
    }
    }
     public void fillTable(){
        DuongBayGUI gui = new DuongBayGUI();
        DefaultTableModel tblmodel = (DefaultTableModel)gui.tbl_DuongBay.getModel();
        tblmodel.setRowCount(0);
        int stt=1;
        for(DuongBayDTO db : dao.getALL()){
            Object data [] = new Object[5];
            data[0]=stt++;
            data[1]=db.getMaDuongBay();
            data[2]=db.getNoiDi();
            data[3]=db.getNoiDen();
            data[4]=db.getThoiGianBay();
            tblmodel.addRow(data);
        }
    }
    
     public ArrayList<String> getThanhPho(){
        ArrayList<String> tp = new ArrayList<>();
        String[] tp1={"Hà Giang","Cao Bằng","Lào Cai","Sơn La","Lai Châu","Bắc Kạn","Lạng Sơn","Tuyên Quang","Yên Bái","Thái Nguyên","Điện Biên","Phú Thọ","Vĩnh Phúc","Bắc Giang","Bắc Ninh","Hà Nội","Quảng Ninh","Hải Dương","Hải Phòng","Hòa Bình","Hưng Yên","Hà Nam","Thái Bình","Nam Định","Ninh Bình","Thanh Hóa","Nghệ An","Hà Tĩnh","Quảng Bình","Quảng Trị","Thừa Thiên Huế","Đà Nẵng","Quảng Nam","Quảng Ngãi","Kon Tum","Gia Lai","Bình Định","Phú Yên","Đắk Lắk","Khánh Hòa","Đắk Nông",	"Lâm Đồng",	"Ninh Thuận",	"Bình Phước",	"Tây Ninh",	"Bình Dương",	"Đồng Nai",	"Bình Thuận",	"Thành phố Hồ Chí Minh",	"Long An",	"Bà Rịa – Vũng Tàu",	"Đồng Tháp",	"An Giang",	"Tiền Giang",	"Vĩnh Long",	"Bến Tre",	"Cần Thơ",	"Kiên Giang",	"Trà Vinh",	"Hậu Giang",	"Sóc Trăng",	"Bạc Liêu",	"Cà Mau",
};
        for (String y: tp1){
            tp.add(y);
        }
         return tp;  
    }
      public void showComfirmRemove(){
        if (JOptionPane.showConfirmDialog(this, "Bạn chắc chứ?", "Question", 2) == 0) {
            String maDB = txt_maDB1.getText();
            if(dao.undoldel(maDB)>1){
                JOptionPane.showMessageDialog(this, "Khôi phục thành công");
            }
        }
    }
      public void fillTable1(){
        DuongBayGUI gui = new DuongBayGUI(); 
        DefaultTableModel tblmodel = (DefaultTableModel)gui.tbl_DuongBay.getModel();
        tblmodel.setRowCount(0);
        int stt=1;
        for(DuongBayDTO db : dao.getAllActive()){
            Object data [] = new Object[5];
            data[0]=stt++;
            data[1]=db.getMaDuongBay();
            data[2]=db.getNoiDi();
            data[3]=db.getNoiDen();
            data[4]=db.getThoiGianBay();
            tblmodel.addRow(data);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbo_noiDen1;
    private javax.swing.JComboBox<String> cbo_noiDi1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSpinner spn_giay1;
    private javax.swing.JSpinner spn_gio1;
    private javax.swing.JSpinner spn_phut1;
    public javax.swing.JTextField txt_maDB1;
    // End of variables declaration//GEN-END:variables
}
