/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import DAO.CauTrucBusDAO;
import DAO.CauTrucEcoDAO;
import static DAO.DBConnect.getConnection;
import DAO.HangBayDAO;
import DAO.KichThuocDAO;
import DAO.MayBayDAO;
import DTO.CauTrucBus;
import DTO.CauTrucEco;
import DTO.MayBayDTO;
import java.awt.Color;
import java.awt.Component;
import java.awt.HeadlessException;
import java.sql.SQLException;
import java.text.ParseException;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author DELL
 */
public class ThemMayBay extends javax.swing.JFrame {
    int max=0,min=0,max2=0,min2=0;;
    KichThuocDAO daoKichThuoc = new KichThuocDAO();
    HangBayDAO daoHangBay = new HangBayDAO();
    CauTrucBusDAO daoCauTrucBus = new CauTrucBusDAO();
    CauTrucEcoDAO daoCauTrucEco = new CauTrucEcoDAO();
    MayBayDAO daoMB = new MayBayDAO();

    @Override
    public void setLocationRelativeTo(Component c) {
        super.setLocationRelativeTo(c); 
    }

    public ThemMayBay() throws SQLException {
        initComponents();
        setLocationRelativeTo(null);
        getDataCombobox();
        MayBayDAO dao= new MayBayDAO();
        int stt=dao.getSLMayBay()+1;
        txtMaMB.setEditable(false);
        txtMaMB.setText("VN-A00"+stt);
    }

    public void getDataCombobox() {
        cboKichThuoc.addItem("Kích thước");
        cboKichThuoc.addItem("Lớn");
        cboKichThuoc.addItem("Vừa");
        cboKichThuoc.addItem("Nhỏ");
        cboHangBay.addItem("Hãng bay");
        cboHangBay.addItem("Vietjet Air");
        cboHangBay.addItem("Vietnam Airlines");
        cboHangBay.addItem("Jetstar Pacific");
        cboHangBay.addItem("Bamboo");

}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        MaMB = new javax.swing.JLabel();
        HangBay = new javax.swing.JLabel();
        KichThuoc = new javax.swing.JLabel();
        btnReturn = new javax.swing.JButton();
        txtMaMB = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        cboHangBay = new javax.swing.JComboBox<>();
        cboKichThuoc = new javax.swing.JComboBox<>();
        CTB = new javax.swing.JLabel();
        SLB = new javax.swing.JLabel();
        CTE = new javax.swing.JLabel();
        cboCTB = new javax.swing.JComboBox<>();
        cboCTE = new javax.swing.JComboBox<>();
        SLE = new javax.swing.JLabel();
        txtSLbus = new javax.swing.JTextField();
        txtSLeco = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));

        MaMB.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        MaMB.setText("Mã máy bay");

        HangBay.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        HangBay.setText("Hãng bay");

        KichThuoc.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        KichThuoc.setText("Kích thước");

        btnReturn.setBackground(new java.awt.Color(0, 153, 255));
        btnReturn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnReturn.setForeground(new java.awt.Color(255, 255, 255));
        btnReturn.setText("Về");
        btnReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnActionPerformed(evt);
            }
        });

        txtMaMB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaMBActionPerformed(evt);
            }
        });

        btnSave.setBackground(new java.awt.Color(0, 153, 255));
        btnSave.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("Lưu");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        cboKichThuoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboKichThuocActionPerformed(evt);
            }
        });

        CTB.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CTB.setText("CauTrucBus");

        SLB.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        SLB.setText("SLBussiness");

        CTE.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CTE.setText("CauTrucEco");

        cboCTB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboCTBActionPerformed(evt);
            }
        });

        SLE.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        SLE.setText("SLEconomy");

        txtSLbus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSLbusActionPerformed(evt);
            }
        });

        txtSLeco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSLecoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MaMB, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(KichThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HangBay, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CTB, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SLB, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CTE, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SLE)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 124, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(cboKichThuoc, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtMaMB)
                    .addComponent(cboCTB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cboCTE, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtSLbus)
                    .addComponent(txtSLeco)
                    .addComponent(btnReturn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboHangBay, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(90, 90, 90))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MaMB, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaMB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(KichThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboKichThuoc))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HangBay, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboHangBay, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CTB, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboCTB, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CTE, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboCTE, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SLB, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSLbus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSLeco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SLE))
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReturn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(84, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setBackground(new java.awt.Color(153, 255, 255));
        jPanel2.setToolTipText("");
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Thêm Máy Bay");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(162, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        setBounds(0, 0, 453, 564);
    }// </editor-fold>//GEN-END:initComponents

    private void btnReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnActionPerformed
        MayBayPanel view=new MayBayPanel();
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReturnActionPerformed
public boolean checkvalidateForm(){
        if(txtMaMB.getText().isEmpty()
                ||txtSLbus.getText().isEmpty()
                ||txtSLeco.getText().isEmpty()
                ||cboCTB.getSelectedIndex()==0
                ||cboCTE.getSelectedIndex()==0
                ||cboHangBay.getSelectedIndex()==0
                ||cboKichThuoc.getSelectedIndex()==0
                ){      
            return false;
        }
        return true;
    }
    
 public ThemMayBay(JLabel CTB, JLabel CTE, JLabel HangBay, JLabel KichThuoc, JLabel MaMB, JLabel SLB, JLabel SLE, JButton btnReturn, JButton btnSave, JComboBox<String> cboCTB, JComboBox<String> cboCTE, JComboBox<String> cboHangBay, JComboBox<String> cboKichThuoc, JLabel jLabel1, JPanel jPanel1, JPanel jPanel2, JTextField txtMaMB, JTextField txtSLB, JTextField txtSLE) throws HeadlessException {
        this.CTB = CTB;
        this.CTE = CTE;
        this.HangBay = HangBay;
        this.KichThuoc = KichThuoc;
        this.MaMB = MaMB;
        this.SLB = SLB;
        this.SLE = SLE;
        this.btnReturn = btnReturn;
        this.btnSave = btnSave;
        this.cboCTB = cboCTB;
        this.cboCTE = cboCTE;
        this.cboHangBay = cboHangBay;
        this.cboKichThuoc = cboKichThuoc;
        this.jLabel1 = jLabel1;
        this.jPanel1 = jPanel1;
        this.jPanel2 = jPanel2;
        this.txtMaMB = txtMaMB;
        this.txtSLbus = txtSLB;
        this.txtSLeco = txtSLE;
    }

 
 public MayBayDTO getModel() throws SQLException {
    MayBayDTO mb = new MayBayDTO();
    MayBayDAO dao = new MayBayDAO();
    int stt = dao.getSLMayBay();
    stt++;
    mb.setMaMayBay("VN-A0" + stt);
    String maMayBay = txtMaMB.getText().trim();
    String kichThuoc = cboKichThuoc.getSelectedItem().toString();
    String hangbay =  cboHangBay.getSelectedItem().toString();
    String cautrucBus =  cboCTB.getSelectedItem().toString();
    String cautrucEco =  cboCTE.getSelectedItem().toString();
    int bus=Integer.parseInt(txtSLbus.getText());
    int eco=Integer.parseInt(txtSLeco.getText());
    if(kichThuoc.equals("Lớn")) {
            min=60;
            max=40;
            min2=150;
            max2=180;
    } else if(kichThuoc.equals("Vừa")) {
            min=30;
            max=45;
            min2=100;
            max2=135;
    } else {
            min=20;
            max=25;
            min2=60;
            max2=75;
        
    }
    mb.setCautrucBus(cautrucBus);
    mb.setCautrucEco(cautrucEco);
    mb.setHangBay(hangbay);
    mb.setKichThuoc(kichThuoc);
    mb.setMaMayBay(maMayBay);
    mb.setSLbus(bus);
    mb.setSLeco(eco);
    mb.setXuLy(1);
     return mb;
    
}



    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
                                        
if (!checkvalidateForm()) {
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập đầy đủ thông tin");
        } else {
    try {
        MayBayDTO mb = getModel();
        if (mb != null) {
            MayBayDAO daoMB = new MayBayDAO();
            if(min<=mb.getSLbus() && mb.getSLbus()<=max && min2<=mb.getSLeco() && mb.getSLeco()<=max2) {
                int result = daoMB.InsertMayBay(mb);
                if (result > 0) {
                    seatSetting.addGhe(mb.getMaMayBay());
                    JOptionPane.showMessageDialog(this, "Lưu dữ liệu  thành công");
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(this, "Lưu dữ liệu không thành công");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Số lượng bus từ "+min+" đến "+max+"\n Số lượng eco từ "+min2+" đến "+max2);
            }
            
        }
    } catch (SQLException ex) {
        Logger.getLogger(ThemMayBay.class.getName()).log(Level.SEVERE, null, ex);
    } catch (ParseException ex) {
        Logger.getLogger(ThemMayBay.class.getName()).log(Level.SEVERE, null, ex);
    }
        }


    }//GEN-LAST:event_btnSaveActionPerformed
    
    private void txtMaMBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaMBActionPerformed
 
    }//GEN-LAST:event_txtMaMBActionPerformed

    private void txtSLbusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSLbusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSLbusActionPerformed

    private void txtSLecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSLecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSLecoActionPerformed

    private void cboKichThuocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboKichThuocActionPerformed
        // TODO add your handling code here:
        if(cboKichThuoc.getSelectedIndex()==0) {
            cboCTB.removeAllItems();
            cboCTE.removeAllItems();
            cboCTB.addItem("Cấu trúc khoang bus");
            cboCTE.addItem("Cấu trúc khoang eco");
        } else if(cboKichThuoc.getSelectedIndex()==1) {
            cboCTB.removeAllItems();
            cboCTE.removeAllItems();
            cboCTB.addItem("Cấu trúc khoang bus");
            cboCTB.addItem("1-1-0");
            cboCTB.addItem("2-2-0");
            cboCTE.addItem("Cấu trúc khoang eco");
            cboCTE.addItem("2-3-2");
            cboCTE.addItem("3-3-0");
        } else if(cboKichThuoc.getSelectedIndex()==2) {
            cboCTB.removeAllItems();
            cboCTE.removeAllItems();
            cboCTB.addItem("Cấu trúc khoang bus");
            cboCTB.addItem("1-1-0");
            cboCTB.addItem("2-2-0");
            cboCTE.addItem("Cấu trúc khoang eco");
            cboCTE.addItem("3-3-0");
        } else {
            cboCTB.removeAllItems();
            cboCTE.removeAllItems();
            cboCTB.addItem("Cấu trúc khoang bus");
            cboCTB.addItem("1-1-0");
            cboCTE.addItem("Cấu trúc khoang eco");
            cboCTE.addItem("2-2-0");
        } 
        
    }//GEN-LAST:event_cboKichThuocActionPerformed

    private void cboCTBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboCTBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboCTBActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CTB;
    private javax.swing.JLabel CTE;
    private javax.swing.JLabel HangBay;
    private javax.swing.JLabel KichThuoc;
    private javax.swing.JLabel MaMB;
    private javax.swing.JLabel SLB;
    private javax.swing.JLabel SLE;
    private javax.swing.JButton btnReturn;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cboCTB;
    private javax.swing.JComboBox<String> cboCTE;
    private javax.swing.JComboBox<String> cboHangBay;
    private javax.swing.JComboBox<String> cboKichThuoc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtMaMB;
    private javax.swing.JTextField txtSLbus;
    private javax.swing.JTextField txtSLeco;
    // End of variables declaration//GEN-END:variables


    private boolean validateForm() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}