/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.ThanhToanGUI;
import GUI.datve.createHoaDon;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author Thanh Tran
 */
public class Bank extends javax.swing.JPanel {

    /**
     * Creates new form Bank
     */
    public Bank() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnMua = new javax.swing.JButton();
        jLabel68 = new javax.swing.JLabel();
        cbxBank = new javax.swing.JComboBox<>();
        jLabel69 = new javax.swing.JLabel();
        txtSotheBank = new javax.swing.JTextField();
        jLabel70 = new javax.swing.JLabel();
        txtHotenBank = new javax.swing.JTextField();
        jLabel73 = new javax.swing.JLabel();
        txtCVCBank = new javax.swing.JTextField();
        jLabel71 = new javax.swing.JLabel();
        cbxThanghethanBank = new javax.swing.JComboBox<>();
        cbxNamhethanBank = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(450, 501));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(598, 508));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/asset/warn.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 153, 0));
        jLabel3.setText("Lưu ý :");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel2.setText("Trường bắt buộc nhập thông tin (*)");

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        btnMua.setBackground(new java.awt.Color(0, 245, 225));
        btnMua.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnMua.setForeground(new java.awt.Color(255, 255, 255));
        btnMua.setText("Thanh Toán");
        btnMua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMuaActionPerformed(evt);
            }
        });

        jLabel68.setForeground(new java.awt.Color(255, 0, 0));
        jLabel68.setText("Ngân hàng (*)");

        cbxBank.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chọn ngân hàng", "Ngân hàng ACB", "Ngân hàng Agribank", "Ngân hàng BIDV", "Ngân hàng DongA Bank", "Ngân hàng GPBank", "Ngân hàng HDBank", "Ngân hàng Maritimebank", "Ngân hàng MBBank", "Ngân hàng Sacombank", "Ngân hàng SCB", "Ngân hàng SeABank", "Ngân hàng Techcombank", "Ngân hàng TPBank", "Ngân hàng VIB", "Ngân hàng Vietcombank", "Ngân hàng VietinBank", "Ngân hàng VPBank", " ", " ", " ", " ", " " }));

        jLabel69.setForeground(new java.awt.Color(255, 0, 0));
        jLabel69.setText("Nhập số thẻ (*)");

        txtSotheBank.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel70.setForeground(new java.awt.Color(255, 0, 51));
        jLabel70.setText("Nhập tên (*)");

        txtHotenBank.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel73.setForeground(new java.awt.Color(255, 0, 0));
        jLabel73.setText("Nhập CVC (*)");

        jLabel71.setForeground(new java.awt.Color(255, 0, 51));
        jLabel71.setText("Ngày hết hạn (*)");

        cbxThanghethanBank.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MM", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));

        cbxNamhethanBank.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "YYYY", "2025", "2026", "2027", "2028", "2029", "2030" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSotheBank, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel71)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(cbxThanghethanBank, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(19, 19, 19)
                                        .addComponent(cbxNamhethanBank, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel69))
                                .addGap(26, 26, 26)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel73)
                                    .addComponent(txtCVCBank, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel68)
                                    .addComponent(cbxBank, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(73, 73, 73)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel70)
                                    .addComponent(txtHotenBank, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(btnMua, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel68)
                    .addComponent(jLabel70))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtHotenBank, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cbxBank)
                        .addGap(4, 4, 4)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel69)
                    .addComponent(jLabel73))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSotheBank, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCVCBank, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel71)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxThanghethanBank, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxNamhethanBank, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnMua, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(282, 282, 282))
        );

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnMuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMuaActionPerformed
        String[] theBank = txtSotheBank.getText().replaceAll("\\s", "").split("");

                            String[] cvc = txtCVCBank.getText().replaceAll("\\s","").split("");
                           
        if(checkBank(cbxBank.getSelectedItem().toString()) == false){
                    JOptionPane.showMessageDialog(null, "Vui Lòng Chọn Ngân Hàng","Thông báo",JOptionPane.OK_OPTION);
        }
        else if(checkHotenBank_Empty(txtHotenBank.getText()) == false){
                    JOptionPane.showMessageDialog(null, "Vui Lòng Nhập Họ Tên","Thông báo",JOptionPane.OK_OPTION);
        }
        else if(checkHotenBank_DinhDang(txtHotenBank.getText()) == false){
                                JOptionPane.showMessageDialog(null, "Vui Lòng Nhập Lại Họ Tên","Thông báo",JOptionPane.OK_OPTION);
                                txtHotenBank.setText("");
        }
        else if(checkSotheBank_Empty(txtSotheBank.getText()) == false){
                                JOptionPane.showMessageDialog(null, "Vui Lòng Nhập Số Thẻ","Thông báo",JOptionPane.OK_OPTION);
        }
        else if(checkSotheBank_DinhDang(theBank) == false){
            JOptionPane.showMessageDialog(null, "Vui Lòng Nhập Lại Số Thẻ","Thông báo",JOptionPane.OK_OPTION);
            txtSotheBank.setText("");
        }
        else if(checkCVCBank_Empty(txtCVCBank.getText()) == false){
                                            JOptionPane.showMessageDialog(null, "Vui Lòng Nhập Số CVC","Thông báo",JOptionPane.OK_OPTION);

        }
        else if(checkCVCBank_DinhDang(cvc) == false){
                                            JOptionPane.showMessageDialog(null, "Vui Lòng Nhập Lại Số CVC","Thông báo",JOptionPane.OK_OPTION);
                                            txtCVCBank.setText("");
        }
        else if(checkThanghethanBank(cbxThanghethanBank.getSelectedItem().toString()) == false){
                                            JOptionPane.showMessageDialog(null, "Vui Lòng Chọn Tháng Hết Hạn","Thông báo",JOptionPane.OK_OPTION);

        }
        else if(checkNamhethanBank(cbxNamhethanBank.getSelectedItem().toString()) == false){
                                        JOptionPane.showMessageDialog(null, "Vui Lòng Chọn Năm Hết Hạn","Thông báo",JOptionPane.OK_OPTION);

        }
        else{
            ThanhToan.btnVisa.setEnabled(false);
            ThanhToan.btnBank.setEnabled(false);
            ThanhToan.btnMomo.setEnabled(false);
            ThanhToan.btnCash.setEnabled(false);
            ThanhToan.btnDong.setEnabled(true);
            ThanhToan.btnTroVe.setEnabled(false);
            btnMua.setEnabled(false);
            setDefault();
            try {
                new createHoaDon().createHD();
            } catch (SQLException | ParseException ex) {
                Logger.getLogger(Cash.class.getName()).log(Level.SEVERE, null, ex);
            }
            JOptionPane.showMessageDialog(null, "Thanh Toán Thành Công", "Thông Báo", JOptionPane.OK_OPTION);
        }
    }//GEN-LAST:event_btnMuaActionPerformed
    //HÀM KIỂM TRA XEM CÓ CHỨA CHỮ SỐ KHÔNG ?
    private static boolean containsNumbers(String input) {
    // Kiểm tra xem có chứa số không
    Pattern pattern = Pattern.compile("[0-9]");
    Matcher matcher = pattern.matcher(input);
    return matcher.find();
}
    //HÀM KIỂM TRA XEM CÓ CHỨA CHỮ CÁI NÀO KHÔNG ?
    private static boolean containsLetters(String[] input) {
        // Kiểm tra từng phần tử của mảng xem có chứa chữ cái không
        Pattern pattern = Pattern.compile("[a-zA-Z]");

        for (String str : input) {
            Matcher matcher = pattern.matcher(str);
            if (matcher.find()) {
                return true; // Nếu có chữ cái trong bất kỳ phần tử nào, trả về true
            }
        }

        return false; // Nếu không có chữ cái trong mảng, trả về false
    }

        //HÀM KIỂM TRA XEM CÓ CHỨA CHỮ CÁI VIẾT THƯỜNG NÀO KHÔNG ?
    private static boolean containsLowercaseLetters(String input) {
        // Kiểm tra xem có chữ cái viết thường không
        return !input.equals(input.toUpperCase());
    }
    
    //HÀM KIỂM TRA KHÁCH HÀNG CÓ CHỌN NGÂN HÀNG KHÔNG ?
    public static boolean checkBank(String bank){
        if(bank.equals("Chọn ngân hàng"))
        {
                    return false;        
        }
        return true;
    }
    
    //HÀM KIỂM TRA HỌ TÊN CÓ ĐỂ TRỐNG KHÔNG ?
    public static boolean checkHotenBank_Empty(String hten){
        if(hten.equals("")){
                    return false;
        }
        return true;
    }
    
    //HÀM KIỂM TRA ĐỊNH DẠNG NHẬP HỌ TÊN
    public static boolean checkHotenBank_DinhDang(String hten){
         if(containsNumbers(hten) || containsLowercaseLetters(hten)){
                                return false;
        }
        return true;
    }
    
    //HÀM KIỂM TRA SỐ THẺ BANK CÓ ĐỂ TRỐNG KHÔNG ?
    public static boolean checkSotheBank_Empty(String sothe){
         if(sothe.equals("")){
             return false;
        }
         return true;
    }
    
    //HÀM KIỂM TRA ĐỊNH DẠNG NHẬP SỐ THẺ BANK
    public static boolean checkSotheBank_DinhDang(String[] sothe){
         if(sothe.length > 12 || sothe.length < 12){
            return false;
        }
         else if(containsLetters(sothe)){
             return false;
         }
         return true;
    }
    
    //HÀM KIỂM TRA SỐ CVC CÓ ĐỂ TRỐNG KHÔNG ?
    public static boolean checkCVCBank_Empty(String cvc){
         if(cvc.equals("")){
             return false;
        }
         return true;
    }
    
    //HÀM KIỂM TRA ĐỊNH DẠNG NHẬP CVC BANK
    public static boolean checkCVCBank_DinhDang(String[] cvc){
     
         if(cvc.length > 3 || cvc.length < 3){
            return false;
        }
         else if(containsLetters(cvc)){
             return false;
         }
         return true;
    }
    
    //HÀM KIỂM TRA KHÁCH HÀNG CÓ CHỌN THÁNG HẾT HẠN THẺ KHÔNG ?
    public static boolean checkThanghethanBank(String month){
         if(month.equals("MM")){
return false;
        }
         return true;
    }
    
    //HÀM KIỂM TRA KHÁCH HÀNG CÓ CHỌN NĂM HẾT HẠN THẺ KHÔNG ?
    public static boolean checkNamhethanBank(String year){
         if(year.equals("YYYY")){
return false;
        }
         return true;
    }
    
    //HÀM XÉT CÁC Ô TXT VÀ COMBOBOX VỀ TRẠNG THÁI BAN ĐẦU VÀ RỖNG
    public void setDefault(){
        txtHotenBank.setText("");
        txtSotheBank.setText("");
        txtCVCBank.setText("");
        cbxBank.getModel().setSelectedItem("Chọn ngân hàng");
        cbxThanghethanBank.getModel().setSelectedItem("MM");
        cbxNamhethanBank.getModel().setSelectedItem("YYYY");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMua;
    private javax.swing.JComboBox<String> cbxBank;
    private javax.swing.JComboBox<String> cbxNamhethanBank;
    private javax.swing.JComboBox<String> cbxThanghethanBank;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txtCVCBank;
    private javax.swing.JTextField txtHotenBank;
    private javax.swing.JTextField txtSotheBank;
    // End of variables declaration//GEN-END:variables
}
