/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.ThanhToanGUI;
import GUI.datve.MenuDatVe;
import GUI.datve.createHoaDon;
import java.awt.Color;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Thanh Tran
 */
public class Cash extends javax.swing.JPanel {

    /**
     * Creates new form Cash
     */
    public Cash() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtfkhach = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtThoi = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnMua = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(550, 500));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(205, 228, 225));
        jPanel1.setPreferredSize(new java.awt.Dimension(589, 500));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel10.setBackground(new java.awt.Color(205, 228, 225));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 95, 110));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Thanh Toán Trực Tiếp");
        jLabel10.setPreferredSize(new java.awt.Dimension(188, 50));
        jPanel1.add(jLabel10, java.awt.BorderLayout.PAGE_START);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Tiền khách đưa");

        jtfkhach.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        jtfkhach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfkhachActionPerformed(evt);
            }
        });

        jLabel2.setText("Tiền thối lại");

        txtThoi.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtfkhach, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                    .addComponent(txtThoi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(301, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfkhach, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtThoi, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, java.awt.BorderLayout.CENTER);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(589, 120));

        btnMua.setBackground(new java.awt.Color(0, 245, 225));
        btnMua.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnMua.setForeground(new java.awt.Color(255, 255, 255));
        btnMua.setText("Thanh Toán");
        btnMua.setPreferredSize(new java.awt.Dimension(150, 50));
        btnMua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMuaActionPerformed(evt);
            }
        });
        jPanel2.add(btnMua);

        jPanel1.add(jPanel2, java.awt.BorderLayout.PAGE_END);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnMuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMuaActionPerformed
        if (jtfkhach.getText().isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Chưa Nhập Số Tiền Khách Đưa", "Thông Báo", JOptionPane.PLAIN_MESSAGE);
                }
                else if (!isNumber(jtfkhach.getText())) {
                    JOptionPane.showMessageDialog(null, "Phải Nhập Đúng Định Dạng Chữ Số", "Thông Báo", JOptionPane.PLAIN_MESSAGE);
                }    
                else if (jtfkhach.getText().length() > 9) {
                    JOptionPane.showMessageDialog(null, "Số Quá Lớn", "Thông Báo", JOptionPane.PLAIN_MESSAGE);
                } 
                else if (Long.parseLong(jtfkhach.getText()) < Long.parseLong(ThanhToan.txtTotal.getText()+"")) {
                    JOptionPane.showMessageDialog(null, "Số Tiền Khách Đưa Không Đủ", "Thông Báo", JOptionPane.PLAIN_MESSAGE);
                }  else {
                    long thoi = Long.parseLong(jtfkhach.getText()) - Long.parseLong(ThanhToan.txtTotal.getText()+"");
                    txtThoi.setText("" + thoi);
                    ThanhToan.btnVisa.setEnabled(false);
                    ThanhToan.btnBank.setEnabled(false);
                    ThanhToan.btnMomo.setEnabled(false);
                    ThanhToan.btnCash.setEnabled(false);
                    ThanhToan.btnDong.setEnabled(true);
                    ThanhToan.btnTroVe.setEnabled(false);
                    btnMua.setEnabled(false);
                    try {
                        new createHoaDon().createHD();
                    } catch (SQLException | ParseException ex) {
                        Logger.getLogger(Cash.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    JOptionPane.showMessageDialog(null, "Thanh Toán Thành Công", "Thông Báo", JOptionPane.OK_OPTION);
                    //MenuDatVe.setvisible(0);
                }    
    }//GEN-LAST:event_btnMuaActionPerformed

    private void jtfkhachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfkhachActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfkhachActionPerformed
    
public boolean isNumber(String str) {
    return str != null && str.matches("\\d+");
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMua;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jtfkhach;
    private javax.swing.JLabel txtThoi;
    // End of variables declaration//GEN-END:variables
}
