/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI.datve;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.UIManager;

/**
 *
 * @author ANH KHOA
 */
public class Bookve extends javax.swing.JFrame {

    public Bookve() {
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gbtn_ChonChieu = new javax.swing.ButtonGroup();
        jToggleButton1 = new javax.swing.JToggleButton();
        pnNorth = new javax.swing.JPanel();
        pn_Title = new javax.swing.JPanel();
        btn_DatVe = new javax.swing.JButton();
        btn_TTKH = new javax.swing.JButton();
        btn_DVBT = new javax.swing.JButton();
        btn_CCN = new javax.swing.JButton();
        btn_TT = new javax.swing.JButton();
        pn_Center = new javax.swing.JPanel();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(248, 249, 209));
        setLocationByPlatform(true);
        setSize(new java.awt.Dimension(1200, 700));

        pnNorth.setBackground(new java.awt.Color(204, 255, 255));
        pnNorth.setPreferredSize(new java.awt.Dimension(1200, 150));
        pnNorth.setLayout(new java.awt.BorderLayout());

        pn_Title.setBackground(new java.awt.Color(0, 204, 204));
        pn_Title.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        pn_Title.setPreferredSize(new java.awt.Dimension(1200, 20));
        pn_Title.setLayout(new java.awt.GridLayout(1, 0));

        btn_DatVe.setBackground(new java.awt.Color(0, 204, 204));
        btn_DatVe.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_DatVe.setForeground(new java.awt.Color(255, 255, 255));
        btn_DatVe.setText("ĐẶT VÉ");
        pn_Title.add(btn_DatVe);

        btn_TTKH.setBackground(new java.awt.Color(0, 204, 204));
        btn_TTKH.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_TTKH.setForeground(new java.awt.Color(255, 255, 255));
        btn_TTKH.setText("THÔNG TIN HÀNH KHÁCH");
        btn_TTKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TTKHActionPerformed(evt);
            }
        });
        pn_Title.add(btn_TTKH);

        btn_DVBT.setBackground(new java.awt.Color(0, 204, 204));
        btn_DVBT.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_DVBT.setForeground(new java.awt.Color(255, 255, 255));
        btn_DVBT.setText("DỊCH VỤ BỔ TRỢ");
        btn_DVBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DVBTActionPerformed(evt);
            }
        });
        pn_Title.add(btn_DVBT);

        btn_CCN.setBackground(new java.awt.Color(0, 204, 204));
        btn_CCN.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_CCN.setForeground(new java.awt.Color(255, 255, 255));
        btn_CCN.setText("CHỌN CHỖ NGỒI");
        btn_CCN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CCNActionPerformed(evt);
            }
        });
        pn_Title.add(btn_CCN);

        btn_TT.setBackground(new java.awt.Color(0, 204, 204));
        btn_TT.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_TT.setForeground(new java.awt.Color(255, 255, 255));
        btn_TT.setText("THANH TOÁN");
        pn_Title.add(btn_TT);

        pnNorth.add(pn_Title, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnNorth, java.awt.BorderLayout.NORTH);

        pn_Center.setBackground(new java.awt.Color(248, 255, 235));
        pn_Center.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 0, 0, 0));
        pn_Center.setForeground(new java.awt.Color(255, 255, 255));
        pn_Center.setLayout(new java.awt.BorderLayout());
        getContentPane().add(pn_Center, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_TTKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TTKHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_TTKHActionPerformed

    private void btn_DVBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DVBTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_DVBTActionPerformed

    private void btn_CCNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CCNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_CCNActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Bookve.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Bookve.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Bookve.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Bookve.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Bookve().setVisible(true);
//               /* try {
//            // Sử dụng Look and Feel mặc định
//            UIManager.setLookAndFeel("com.sun.java.swing.plaf.motif.MotifLookAndFeel");
//        } catch (Exception e) {
//            e.printStackTrace();
//        }*/
//            }
//        });
//    }
    public void init(){
        setLocationRelativeTo(null);
        Panel_TrangChu pn_DatVe = new Panel_TrangChu();
        pn_Center.add(pn_DatVe,BorderLayout.CENTER);
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_CCN;
    private javax.swing.JButton btn_DVBT;
    private javax.swing.JButton btn_DatVe;
    private javax.swing.JButton btn_TT;
    private javax.swing.JButton btn_TTKH;
    private javax.swing.ButtonGroup gbtn_ChonChieu;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JPanel pnNorth;
    private javax.swing.JPanel pn_Center;
    private javax.swing.JPanel pn_Title;
    // End of variables declaration//GEN-END:variables

}
