/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI.datve;

import DTO.KhachHangDTO;
import DatVeDTO.ButtonDm;
import DatVeDTO.DanhMuc;
import GUI.LeTanGUI.ReceptionistGUI;
import java.awt.CardLayout;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author ANH KHOA
 */
public class MenuDatVe extends javax.swing.JFrame {
    public static CardLayout cardLayout;
    public static String hangghe1C="";
    public static String hangghe2C="";
    public static String Gia1C="";
    public static String Gia2C="";
    public static int khuhoi;
    public static String ma1c="";
    public static String ma2c="";
    public static ArrayList<KhachHangDTO> KHlList;
    public static ArrayList<String> MaGheList;
    public static ArrayList<String> MaGheListVe;
    public static int closeWin;
    /**ii
     * i
     * Creates new form MenuDatVe
     */
    public MenuDatVe(int close) {
        closeWin = close;
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnNorth = new javax.swing.JPanel();
        pn_Title = new javax.swing.JPanel();
        btn_TC = new javax.swing.JButton();
        btn_DatVe = new javax.swing.JButton();
        btn_TTKH = new javax.swing.JButton();
        btn_CCN = new javax.swing.JButton();
        btn_DVBT = new javax.swing.JButton();
        pn_View = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Đặt vé");
        setBackground(new java.awt.Color(255, 255, 255));
        setSize(new java.awt.Dimension(1200, 700));

        pnNorth.setBackground(new java.awt.Color(204, 255, 255));
        pnNorth.setPreferredSize(new java.awt.Dimension(1200, 150));
        pnNorth.setLayout(new java.awt.BorderLayout());

        pn_Title.setBackground(new java.awt.Color(255, 255, 255));
        pn_Title.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 10, 2, new java.awt.Color(255, 255, 255)));
        pn_Title.setPreferredSize(new java.awt.Dimension(1200, 20));
        pn_Title.setLayout(new java.awt.GridLayout(1, 5));

        btn_TC.setBackground(new java.awt.Color(0, 204, 204));
        btn_TC.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_TC.setForeground(new java.awt.Color(255, 255, 255));
        btn_TC.setText("TRANG CHỦ");
        btn_TC.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 2, 0, 2, new java.awt.Color(255, 255, 255)));
        pn_Title.add(btn_TC);

        btn_DatVe.setBackground(new java.awt.Color(0, 204, 204));
        btn_DatVe.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_DatVe.setForeground(new java.awt.Color(255, 255, 255));
        btn_DatVe.setText("CHỌN CHUYẾN BAY");
        btn_DatVe.setBorder(null);
        btn_DatVe.setEnabled(false);
        pn_Title.add(btn_DatVe);

        btn_TTKH.setBackground(new java.awt.Color(0, 204, 204));
        btn_TTKH.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_TTKH.setForeground(new java.awt.Color(255, 255, 255));
        btn_TTKH.setText("THÔNG TIN HÀNH KHÁCH");
        btn_TTKH.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 2, 0, 2, new java.awt.Color(255, 255, 255)));
        btn_TTKH.setEnabled(false);
        btn_TTKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TTKHActionPerformed(evt);
            }
        });
        pn_Title.add(btn_TTKH);

        btn_CCN.setBackground(new java.awt.Color(0, 204, 204));
        btn_CCN.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_CCN.setForeground(new java.awt.Color(255, 255, 255));
        btn_CCN.setText("CHỌN CHỖ NGỒI");
        btn_CCN.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 2, 0, 2, new java.awt.Color(255, 255, 255)));
        btn_CCN.setEnabled(false);
        btn_CCN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CCNActionPerformed(evt);
            }
        });
        pn_Title.add(btn_CCN);

        btn_DVBT.setBackground(new java.awt.Color(0, 204, 204));
        btn_DVBT.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_DVBT.setForeground(new java.awt.Color(255, 255, 255));
        btn_DVBT.setText("DỊCH VỤ BỔ TRỢ");
        btn_DVBT.setBorder(null);
        btn_DVBT.setEnabled(false);
        btn_DVBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DVBTActionPerformed(evt);
            }
        });
        pn_Title.add(btn_DVBT);

        pnNorth.add(pn_Title, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnNorth, java.awt.BorderLayout.NORTH);

        pn_View.setPreferredSize(new java.awt.Dimension(1200, 550));
        pn_View.setLayout(new java.awt.BorderLayout());
        getContentPane().add(pn_View, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_TTKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TTKHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_TTKHActionPerformed

    private void btn_CCNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CCNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_CCNActionPerformed

    private void btn_DVBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DVBTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_DVBTActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public void init(){
        //btnList.add()
//        this.setResizable(false);
        MaGheList=new ArrayList<>();
        MaGheListVe=new ArrayList<>();
        KHlList=new ArrayList<>();
        setVisible(true);
        setLocationRelativeTo(null);
        cardLayout = new CardLayout();
        pn_View.setLayout(cardLayout);
        
        pn_View.add(new Panel_TrangChu(), "page1");
        btn_TC.addActionListener(e ->{
            btn_DatVe.setEnabled(false);
            btn_TTKH.setEnabled(false);
            btn_CCN.setEnabled(false);
            btn_DVBT.setEnabled(false);
            //btn_TT.setEnabled(false);
            
            pn_View.add(new Panel_TrangChu(), "page1");
            cardLayout.show(pn_View, "page1");
        });
        cardLayout.show(pn_View, "page1");
        
        btn_DatVe.addActionListener(e ->{
            btn_TTKH.setEnabled(false);
            btn_CCN.setEnabled(false);
            btn_DVBT.setEnabled(false);
            //btn_TT.setEnabled(false);
            try {
                pn_View.add(new PanelChonChuyenBay(Panel_TrangChu.tcb), "page2");
            } catch (ParseException ex) {
                Logger.getLogger(MenuDatVe.class.getName()).log(Level.SEVERE, null, ex);
            }
            cardLayout.show(pn_View, "page2");
        });
        
        btn_TTKH.addActionListener(e ->{
            btn_CCN.setEnabled(false);
            btn_DVBT.setEnabled(false);
            //btn_TT.setEnabled(false);
            MenuDatVe.MaGheList=new ArrayList<>();
            MenuDatVe.MaGheListVe=new ArrayList<>();
            cardLayout.show(pn_View, "page3");
        });
        
        btn_CCN.addActionListener(e ->{
            btn_DVBT.setEnabled(false);
            //btn_TT.setEnabled(false);
            cardLayout.show(pn_View, "page4");  
        });
        btn_DVBT.addActionListener(e ->{
            cardLayout.show(pn_View, "page5");
            //btn_TT.setEnabled(false);
        });
        //btn_TT.addActionListener(e -> cardLayout.show(pn_View, "page6"));
        // Create the "Chon Cho Ngoi" panel
//        JPanel pnChonChoNgoi = new p();
//        btn_CCN.addActionListener(e -> cardLayout.show(contentPanel, "page4"));

        // Create the "Thanh Toan" panel
        JPanel page4Panel = new JPanel();
        page4Panel.add(new JLabel("Thanh Toan"));

        
//        
//        pn_View.add(new ThanhToan(), "page6");
//        contentPanel.add(page3Panel, "page3");
//        contentPanel.add(page4Panel, "page4");
//        
//    }
        
//        setTitle("Đặt vé");
//        ChuyenManHinhController controller = new ChuyenManHinhController(pn_View);
//        controller.setView2(btn_TC);
//        
//        
    }
public void setvisible(int x){
    if(x==0){
        setVisible(false);
    }else setVisible(true);
}
public void closeWin(){
    addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                // Quay lại JFrame trước đó
                new ReceptionistGUI().setVisible(true);
                dispose(); // Đóng JFrame hiện tại
            }
        });
}
//public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(MenuDatVe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(MenuDatVe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(MenuDatVe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(MenuDatVe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new MenuDatVe();
//            } 
//        });
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btn_CCN;
    public static javax.swing.JButton btn_DVBT;
    public static javax.swing.JButton btn_DatVe;
    public static javax.swing.JButton btn_TC;
    public static javax.swing.JButton btn_TTKH;
    private javax.swing.JPanel pnNorth;
    private javax.swing.JPanel pn_Title;
    public static javax.swing.JPanel pn_View;
    // End of variables declaration//GEN-END:variables
}
