/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.datve;

/**
 *
 * @author ANH KHOA
 */
public class Panel_titileBookVe extends javax.swing.JPanel {

    /**
     * Creates new form Panel_titileBookVe
     */
    public Panel_titileBookVe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnNorth = new javax.swing.JPanel();
        pn_Title = new javax.swing.JPanel();
        btn_DatVe = new javax.swing.JButton();
        btn_TTKH = new javax.swing.JButton();
        btn_DVBT = new javax.swing.JButton();
        btn_CCN = new javax.swing.JButton();
        btn_TT = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1200, 75));
        setLayout(new java.awt.BorderLayout());

        pnNorth.setBackground(new java.awt.Color(204, 255, 255));
        pnNorth.setPreferredSize(new java.awt.Dimension(1200, 150));
        pnNorth.setLayout(new java.awt.BorderLayout());

        pn_Title.setBackground(new java.awt.Color(0, 204, 204));
        pn_Title.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        pn_Title.setPreferredSize(new java.awt.Dimension(1200, 20));
        pn_Title.setLayout(new java.awt.GridLayout(1, 0));

        btn_DatVe.setBackground(new java.awt.Color(0, 204, 204));
        btn_DatVe.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_DatVe.setForeground(new java.awt.Color(255, 255, 255));
        btn_DatVe.setText("CHỌN CHUYẾN BAY");
        btn_DatVe.setBorder(null);
        pn_Title.add(btn_DatVe);

        btn_TTKH.setBackground(new java.awt.Color(0, 204, 204));
        btn_TTKH.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_TTKH.setForeground(new java.awt.Color(255, 255, 255));
        btn_TTKH.setText("THÔNG TIN HÀNH KHÁCH");
        btn_TTKH.setBorder(null);
        btn_TTKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TTKHActionPerformed(evt);
            }
        });
        pn_Title.add(btn_TTKH);

        btn_DVBT.setBackground(new java.awt.Color(0, 204, 204));
        btn_DVBT.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_DVBT.setForeground(new java.awt.Color(255, 255, 255));
        btn_DVBT.setText("DỊCH VỤ BỔ TRỢ");
        btn_DVBT.setBorder(null);
        btn_DVBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DVBTActionPerformed(evt);
            }
        });
        pn_Title.add(btn_DVBT);

        btn_CCN.setBackground(new java.awt.Color(0, 204, 204));
        btn_CCN.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_CCN.setForeground(new java.awt.Color(255, 255, 255));
        btn_CCN.setText("CHỌN CHỖ NGỒI");
        btn_CCN.setBorder(null);
        btn_CCN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CCNActionPerformed(evt);
            }
        });
        pn_Title.add(btn_CCN);

        btn_TT.setBackground(new java.awt.Color(0, 204, 204));
        btn_TT.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_TT.setForeground(new java.awt.Color(255, 255, 255));
        btn_TT.setText("THANH TOÁN");
        btn_TT.setBorder(null);
        pn_Title.add(btn_TT);

        pnNorth.add(pn_Title, java.awt.BorderLayout.CENTER);

        add(pnNorth, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_TTKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TTKHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_TTKHActionPerformed

    private void btn_DVBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DVBTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_DVBTActionPerformed

    private void btn_CCNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CCNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_CCNActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_CCN;
    private javax.swing.JButton btn_DVBT;
    private javax.swing.JButton btn_DatVe;
    private javax.swing.JButton btn_TT;
    private javax.swing.JButton btn_TTKH;
    private javax.swing.JPanel pnNorth;
    private javax.swing.JPanel pn_Title;
    // End of variables declaration//GEN-END:variables
}
