/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.datve;

import BUS.KhachHangBUS;
import BUS.NhanVienBUS;
import DTO.KhachHangDTO;
import java.awt.Color;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.text.AbstractDocument;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.DocumentFilter;

/**
 *
 * @author ANH KHOA
 */
 class UppercaseDocumentFilter extends DocumentFilter {

    @Override
    public void insertString(FilterBypass fb, int offset, String text, AttributeSet attr) throws BadLocationException {
        fb.insertString(offset, text.toUpperCase(), attr);
    }

    @Override
    public void replace(FilterBypass fb, int offset, int length, String text, AttributeSet attrs) throws BadLocationException {
        fb.replace(offset, length, text.toUpperCase(), attrs);
    }
 }


public class Panel_ContentKh extends javax.swing.JPanel {
    String Type;
    KhachHangBUS khbus = new KhachHangBUS();
    /**
     * Creates new form Panel_ContentKh
     */
    public Panel_ContentKh(String type, int count) {
        initComponents();
        ((AbstractDocument) jtfMa.getDocument()).setDocumentFilter(new UppercaseDocumentFilter());
        jtfMa.setText(null);
        init(type, count);
        Type = type;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnContentCenter = new javax.swing.JPanel();
        jtf_sdt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtf_email = new javax.swing.JTextField();
        jtf_cccd = new javax.swing.JTextField();
        jtf_tenvstendem = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jdc_Ngaysinh = new com.toedter.calendar.JDateChooser();
        cb_GioiTinh = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lb_TTHK = new javax.swing.JLabel();
        jtfMa = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1200, 325));
        setLayout(new java.awt.BorderLayout());

        pnContentCenter.setBackground(new java.awt.Color(248, 255, 235));
        pnContentCenter.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 20, 0, new java.awt.Color(255, 255, 255)));
        pnContentCenter.setPreferredSize(new java.awt.Dimension(1000, 275));

        jtf_sdt.setPreferredSize(new java.awt.Dimension(75, 25));

        jLabel5.setText("Ngày sinh");
        jLabel5.setPreferredSize(new java.awt.Dimension(60, 20));

        jtf_email.setPreferredSize(new java.awt.Dimension(75, 25));

        jtf_cccd.setPreferredSize(new java.awt.Dimension(75, 25));

        jtf_tenvstendem.setPreferredSize(new java.awt.Dimension(75, 25));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Thông tin cơ bản");

        jLabel2.setText("Họ và tên");
        jLabel2.setPreferredSize(new java.awt.Dimension(60, 20));

        jLabel6.setText("Căn cước công dân");
        jLabel6.setPreferredSize(new java.awt.Dimension(30, 20));

        jdc_Ngaysinh.setBackground(new java.awt.Color(248, 255, 235));
        jdc_Ngaysinh.setPreferredSize(new java.awt.Dimension(75, 25));
        LocalDate dateDefault = java.time.LocalDate.now();
        Date date = java.sql.Date.valueOf(dateDefault);
        jdc_Ngaysinh.setDate(date);
        jdc_Ngaysinh.setDateFormatString("dd-MM-yyyy");

        cb_GioiTinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ", " " }));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Thông tin liên hệ");
        jLabel7.setPreferredSize(new java.awt.Dimension(90, 16));

        jLabel8.setText("Số điện thoại");
        jLabel8.setPreferredSize(new java.awt.Dimension(60, 20));

        jLabel9.setText("Email");
        jLabel9.setPreferredSize(new java.awt.Dimension(60, 20));

        jLabel4.setText("Giới tính");
        jLabel4.setPreferredSize(new java.awt.Dimension(90, 30));

        lb_TTHK.setBackground(new java.awt.Color(248, 255, 235));
        lb_TTHK.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_TTHK.setText("Người lớn 1 (người lớn)");
        lb_TTHK.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 10, 0, 0, new java.awt.Color(248, 255, 235)));
        lb_TTHK.setPreferredSize(new java.awt.Dimension(1000, 50));

        jtfMa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfMaActionPerformed(evt);
            }
        });

        jLabel3.setText("Mã khách hàng thân thiết");

        javax.swing.GroupLayout pnContentCenterLayout = new javax.swing.GroupLayout(pnContentCenter);
        pnContentCenter.setLayout(pnContentCenterLayout);
        pnContentCenterLayout.setHorizontalGroup(
            pnContentCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnContentCenterLayout.createSequentialGroup()
                .addComponent(lb_TTHK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 200, Short.MAX_VALUE))
            .addGroup(pnContentCenterLayout.createSequentialGroup()
                .addGroup(pnContentCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnContentCenterLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(pnContentCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnContentCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cb_GioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtf_tenvstendem, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(73, 73, 73)
                        .addGroup(pnContentCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnContentCenterLayout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtf_email, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnContentCenterLayout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(jdc_Ngaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnContentCenterLayout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtf_cccd, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pnContentCenterLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtfMa, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnContentCenterLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(pnContentCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnContentCenterLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jtf_sdt, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnContentCenterLayout.setVerticalGroup(
            pnContentCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnContentCenterLayout.createSequentialGroup()
                .addComponent(lb_TTHK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnContentCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfMa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(pnContentCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnContentCenterLayout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60))
                    .addGroup(pnContentCenterLayout.createSequentialGroup()
                        .addGroup(pnContentCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnContentCenterLayout.createSequentialGroup()
                                .addGroup(pnContentCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtf_tenvstendem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(23, 23, 23))
                            .addGroup(pnContentCenterLayout.createSequentialGroup()
                                .addComponent(jdc_Ngaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)))
                        .addGroup(pnContentCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cb_GioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtf_cccd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)))
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(pnContentCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_sdt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_email, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(245, 245, 245))
        );

        add(pnContentCenter, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jtfMaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfMaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfMaActionPerformed
//    public static void main(String[] args) {
//        new Panel_ContentKh();
//    }
    public void init(String type, int count){
        cb_GioiTinh.setBackground(Color.white);
        jdc_Ngaysinh.setDateFormatString("dd-MM-yyyy");
        jtfMa.addKeyListener(new KeyAdapter() {
            @Override
            public void keyReleased(KeyEvent e) {
                try {
                    loadKHTT(jtfMa.getText());
                } catch (ParseException ex) {
                    Logger.getLogger(Panel_ContentKh.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
        int Lonhon12=0;
        int Tu2den12=0;
        int Nhohon2 =0;
        if(type.equals("Lonhon12")){
            lb_TTHK.setText("Người lớn "+ count+" (người lớn)");
        }
        else if(type.equals("Tu2den12")){
            lb_TTHK.setText("Trẻ em "+ count +" (trẻ em)");
            jLabel6.setVisible(false);
            jtf_cccd.setVisible(false);
            jLabel7.setVisible(false);
            jLabel8.setVisible(false);
            jLabel8.setVisible(false);
            jLabel9.setVisible(false);
            jtf_email.setVisible(false);
            jtf_sdt.setVisible(false);
            
        }
//        else if(type.equals("Nhohon2")){
//            lb_TTHK.setText("Trẻ em "+ count +" (trẻ em dưới 2 tuổi)");
//        }
    }
    public KhachHangDTO add_KH(int key){
        
        KhachHangDTO kh = new KhachHangDTO();
        kh.setMaKH("KH"+key);
        if(Type.equals("Tu2den12")){
            kh.setCccd("");
            kh.setMail("");
            kh.setSdt("");
        }
        else{
            kh.setCccd(jtf_cccd.getText());
            kh.setMail(jtf_email.getText());
            kh.setSdt(jtf_sdt.getText());
        }
        kh.setTenKH(jtf_tenvstendem.getText());
        if(cb_GioiTinh.getSelectedItem().toString().equals("Nam")){
            kh.setGioiTinh(1);
        }
        else  kh.setGioiTinh(0);
         java.util.Date date = jdc_Ngaysinh.getDate();
        SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
        String nsinh = formatter.format(date);
        kh.setNgaySinh(nsinh);
        
//        kh.toString();
//        System.out.println("Mã KH: " + kh.getMaKH());
//        System.out.println("CCCD: " + kh.getCccd());
//        System.out.println("Email: " + kh.getMail());
//        System.out.println("SĐT: " + kh.getSdt());
//        System.out.println("Họ và tên: " + kh.getTenKH());
//        System.out.println("Giới tính: " + kh.getGioiTinh());
        return kh;
        
    }
    public KhachHangDTO add_KH(String key){
        
        KhachHangDTO kh = new KhachHangDTO();
        kh.setMaKH(key);
        if(Type.equals("Tu2den12")){
            kh.setCccd("no");
            kh.setMail("no");
            kh.setSdt("no");
        }
        else{
            kh.setCccd(jtf_cccd.getText());
            kh.setMail(jtf_email.getText());
            kh.setSdt(jtf_sdt.getText());
        }
        kh.setTenKH(jtf_tenvstendem.getText());
        if(cb_GioiTinh.getSelectedItem().toString().equals("Nam")){
            kh.setGioiTinh(1);
        }
        else  kh.setGioiTinh(0);
         java.util.Date date = jdc_Ngaysinh.getDate();
        SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
        String nsinh = formatter.format(date);
        kh.setNgaySinh(nsinh);
        
//        kh.toString();
//        System.out.println("Mã KH: " + kh.getMaKH());
//        System.out.println("CCCD: " + kh.getCccd());
//        System.out.println("Email: " + kh.getMail());
//        System.out.println("SĐT: " + kh.getSdt());
//        System.out.println("Họ và tên: " + kh.getTenKH());
//        System.out.println("Giới tính: " + kh.getGioiTinh());
        return kh;
        
    }
    public  int count() {
        int count = NhanVienBUS.getSize();
        System.out.println(""+count+"\n");
        return count;
    }
    public void loadKHTT(String ma) throws ParseException{
        ArrayList<KhachHangDTO> kh = khbus.loadKH(ma);
        
        if(kh.size()==0) {
            jtf_cccd.setText("");
            jtf_email.setText("");
            jtf_sdt.setText("");
            jtf_tenvstendem.setText("");
            cb_GioiTinh.setSelectedIndex(0);
            Date currentDate = new Date();    
            jdc_Ngaysinh.setDate(currentDate);
        }
        else if(kh.get(0).getMaKH()!=null && kh.get(0).getMaKH().equals(ma)){
            if(Type.equals("Lonhon12")) {
                Calendar calendar = Calendar.getInstance();
                int currentYear = calendar.get(Calendar.YEAR);
                String firstFourChars = kh.get(0).getNgaySinh().substring(kh.get(0).getNgaySinh().length()-4);
                System.out.println(firstFourChars);
                System.out.println(firstFourChars);
                if((currentYear - Integer.parseInt(firstFourChars)) >= 13) {
                    jtf_cccd.setText(kh.get(0).getCccd().trim());
                    jtf_email.setText(kh.get(0).getMail().trim());
                    jtf_sdt.setText(kh.get(0).getSdt().trim());
                    jtf_tenvstendem.setText(kh.get(0).getTenKH().trim());
                    if(kh.get(0).getGioiTinh()==1) cb_GioiTinh.setSelectedIndex(0);
                    else cb_GioiTinh.setSelectedIndex(1);
                    SimpleDateFormat formatter1 = new SimpleDateFormat("dd-mm-yyyy");
                    Date date1 = formatter1.parse(kh.get(0).getNgaySinh());
                    jdc_Ngaysinh.setDate(date1); 
                } else {
                    jtf_cccd.setText("");
                    jtf_email.setText("");
                    jtf_sdt.setText("");
                    jtf_tenvstendem.setText("");
                    cb_GioiTinh.setSelectedIndex(0);
                    Date currentDate = new Date();    
                    jdc_Ngaysinh.setDate(currentDate);
                }
            } else {
                Calendar calendar = Calendar.getInstance();
                int currentYear = calendar.get(Calendar.YEAR);
                String firstFourChars = kh.get(0).getNgaySinh().substring(kh.get(0).getNgaySinh().length()-4);
                System.out.println(firstFourChars);
                if((currentYear - Integer.parseInt(firstFourChars)) >= 2 && (currentYear - Integer.parseInt(firstFourChars)) <= 12 ) {
                    jtf_cccd.setText(kh.get(0).getCccd().trim());
                    jtf_email.setText(kh.get(0).getMail().trim());
                    jtf_sdt.setText(kh.get(0).getSdt().trim());
                    jtf_tenvstendem.setText(kh.get(0).getTenKH().trim());
                    if(kh.get(0).getGioiTinh()==1) cb_GioiTinh.setSelectedIndex(0);
                    else cb_GioiTinh.setSelectedIndex(1);
                    SimpleDateFormat formatter1 = new SimpleDateFormat("dd-mm-yyyy");
                    Date date1 = formatter1.parse(kh.get(0).getNgaySinh());
                    jdc_Ngaysinh.setDate(date1); 
                } else {
                    jtf_cccd.setText("");
                    jtf_email.setText("");
                    jtf_sdt.setText("");
                    jtf_tenvstendem.setText("");
                    cb_GioiTinh.setSelectedIndex(0);
                    Date currentDate = new Date();    
                    jdc_Ngaysinh.setDate(currentDate);
                }
            }
        }
    }
    public String checkKH(){
        return jtfMa.getText();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cb_GioiTinh;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private com.toedter.calendar.JDateChooser jdc_Ngaysinh;
    private javax.swing.JTextField jtfMa;
    private javax.swing.JTextField jtf_cccd;
    private javax.swing.JTextField jtf_email;
    private javax.swing.JTextField jtf_sdt;
    private javax.swing.JTextField jtf_tenvstendem;
    private javax.swing.JLabel lb_TTHK;
    private javax.swing.JPanel pnContentCenter;
    // End of variables declaration//GEN-END:variables
}
